### ISSUE TITLE
Nef fails to generate Playground if path contains spaces

### ISSUE THREAD

**Issue by dfreniche** [bow-swift/nef#121]
# Steps to reproduce

- `cd; cd Desktop`
- `mkdir "test spaces"`
- `cd test\ spaces`
- `nef playground --name test`

You get these errors:
```
Installing Playground (test)...mv: rename /Users/dfreniche/Desktop/nef/test to /Users/dfreniche/Desktop/nef/test spaces/test.app/Contents/MacOS/test: No such file or directory
mv: rename spaces/test.app.1/* to /Users/dfreniche/Desktop/nef/test spaces/test.app/Contents/MacOS/*: No such file or directory
```

and 

```
Installing Playground (test)...mv: rename /Users/dfreniche/Desktop/nef/test to /Users/dfreniche/Desktop/nef/test spaces/test.app/Contents/MacOS/test: No such file or directory
mv: rename spaces/test.app.1/* to /Users/dfreniche/Desktop/nef/test spaces/test.app/Contents/MacOS/*: No such file or directory
```

**Comment by miguelangel-dev** [comment]
Thanks for alert us about it ^^  - currently, we are working in a big architectural refactor. Making `nef` in pure swift (say goodbye to bash scripts) and following a functional-architecture.

When we arrive at project-generator module (it will be the next one) I will take it in mind, to fix the bug. Thanks :)

**Comment by dfreniche** [comment]
Thanks for quick response!

This is not important as in "I'm-stubborn-and-won't-rename-my-folders", renaming folders would be a workaround. Except if you have your Nef Playground stored in iCloud, which is located in `Library/Mobile Documents/com~apple~CloudDocs/`  😁

**Comment by miguelangel-dev** [comment]
Don't worry! It will be ready soon!! It helps to future contributors... :)

**Comment by miguelangel-dev** [comment]
It'll be solved in this [PR](https://github.com/bow-swift/nef/pull/124)

**Comment by miguelangel-dev** [comment]
It has been fixed in this [PR](https://github.com/bow-swift/nef/pull/125)
