### ISSUE TITLE
nef --version

### ISSUE THREAD

**Issue by dfreniche** [bow-swift/nef#127]
Don't know how to check Nef's version number. Tried `nef -v`, `nef -version`, `nef --version` to no avail.

Ideally `nef --version` should return that build's version number

**Comment by miguelangel-dev** [comment]
Thanks ^^, 
this option is available in the current [release](https://github.com/bow-swift/nef/releases/tag/0.5.2), and it has been added to the project in the [attached PR](#129) (it is part of nef refactor, issue #112)
