### ISSUE TITLE
Skip installing pods step

### ISSUE THREAD

**Issue by sloik** [bow-swift/nef#32]
During setup on CI there is a step to install pods so it's redundant. It would be nice to have an option to skip this step :)

**Comment by truizlop** [comment]
We will take a look at it and perhaps only install Pods when they are not already present. Thanks for your feedback!

**Comment by sloik** [comment]
Also building the project/workspace :) I have a setup on CI that runs test so it builds and install all the pods :) It would be great to just add a step that will compile playgrounds :)

btw excellent work with this tool!

**Comment by miguelangel-dev** [comment]
Hi @sloik,

you can see the progress of this issue in [the next PR](https://github.com/bow-swift/nef/pull/39) also you can join us to our [gitter channel](https://gitter.im/bowswift/bow) - see you :)
