### ISSUE TITLE
Relatives url in submenus

### ISSUE THREAD

**Issue by AntonioMateoGomez** [bow-swift/nef#85]
We should set inner nested urls as relative as higher level ones in the docs sidebar menu.

**Comment by miguelangel-dev** [comment]
This has been solved in this [PR](https://github.com/bow-swift/nef/pull/86) right? Could you close this issue?

**Comment by AntonioMateoGomez** [comment]
Yes, I didn´t close it

**Comment by AntonioMateoGomez** [comment]
solved in #86
